import { BRAND, button, emailLayout, escapeHtml, heading, linkFallback, paragraph } from './layout'

const SANS = "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"

const FORMAT_LABEL: Record<string, string> = {
  outline: 'Outline', flashcards: 'Flashcards', quiz: 'Quiz', summary: 'Summary', practice: 'Practice',
  plan: 'Study plan', cheatsheet: 'Cheat sheet', timeline: 'Timeline', custom: 'Study guide',
}

export interface ShareGuideEmail {
  senderName: string | null
  title: string
  format: string
  url: string
  message?: string
  siteUrl: string
}

export function shareGuideEmail(e: ShareGuideEmail): { subject: string; html: string; text: string } {
  const who = e.senderName ? escapeHtml(e.senderName) : 'Someone'
  const title = escapeHtml(e.title)
  const label = FORMAT_LABEL[e.format] ?? 'Study guide'
  const message = e.message?.trim()
    ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 24px 0;">
        <tr><td style="border-left:4px solid ${BRAND.blue};background-color:${BRAND.page};border-radius:0 10px 10px 0;padding:14px 18px;font-family:${SANS};font-size:15px;line-height:23px;color:${BRAND.body};font-style:italic;">
          &ldquo;${escapeHtml(e.message.trim()).replace(/\n/g, '<br>')}&rdquo;
          <div style="margin-top:6px;font-style:normal;font-size:13px;color:${BRAND.muted};">From ${who}</div>
        </td></tr>
      </table>`
    : ''

  const guideCard = `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 28px 0;">
    <tr><td style="border:1px solid ${BRAND.line};border-radius:14px;padding:20px;background-color:#ffffff;">
      <span style="display:inline-block;font-family:${SANS};font-size:11px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;color:${BRAND.blue};background-color:${BRAND.soft};border-radius:999px;padding:4px 10px;">${label}</span>
      <div style="margin-top:10px;font-family:Georgia,'Times New Roman',serif;font-size:21px;line-height:28px;font-weight:600;color:${BRAND.ink};">${title}</div>
    </td></tr>
  </table>`

  const body = [
    heading(`${who} shared a study guide with you`),
    paragraph('Open it to study with flashcards, quizzes and practice. No download needed.', { muted: true }),
    guideCard,
    message,
    button(e.url, 'Open the study guide'),
    '<div style="height:24px;line-height:24px;">&nbsp;</div>',
    linkFallback(e.url),
  ].join('\n')

  return {
    subject: `${e.senderName || 'Someone'} shared “${e.title}” with you`,
    html: emailLayout({
      preheader: `${e.senderName || 'Someone'} shared a ${label.toLowerCase()} with you on Casanova Study.`,
      body,
      footer: `You got this email because ${who} shared a study guide with you on Casanova Study.`,
      siteUrl: e.siteUrl,
    }),
    text: [
      `${e.senderName || 'Someone'} shared a study guide with you: ${e.title}`,
      e.message?.trim() ? `\n"${e.message.trim()}"\n` : '',
      `Open it here: ${e.url}`,
      '',
      'Casanova Study',
    ].join('\n'),
  }
}

// ── Supabase Auth templates ─────────────────────────────────────────────────
// Pasted into Supabase → Authentication → Emails → Templates. They use
// Supabase's Go-template variables, generated by scripts/build-auth-emails.ts.

export function authEmails(siteUrl: string): Record<string, { subject: string; html: string }> {
  const url = '{{ .ConfirmationURL }}'
  const make = (preheader: string, title: string, lead: string, cta: string, note: string) =>
    emailLayout({
      preheader,
      siteUrl,
      footer: 'You got this email because someone used this address on Casanova Study.',
      body: [heading(title), paragraph(lead), '<div style="height:8px;line-height:8px;">&nbsp;</div>', button(url, cta), '<div style="height:24px;line-height:24px;">&nbsp;</div>', paragraph(note, { muted: true, small: true }), linkFallback(url)].join('\n'),
    })
  return {
    'confirm-signup': {
      subject: 'Confirm your Casanova Study account',
      html: make(
        'One click to activate your account.',
        'Welcome to Casanova Study!',
        'You’re one step away from turning your notes, slides and topics into study guides, flashcards and quizzes. Confirm your email to activate your account.',
        'Confirm my email',
        'Didn’t sign up? You can safely ignore this email. No account will be activated.'
      ),
    },
    'reset-password': {
      subject: 'Reset your Casanova Study password',
      html: make(
        'Choose a new password for your account.',
        'Reset your password',
        'We got a request to reset the password for your Casanova Study account. Click below to choose a new one. The link works once and expires soon.',
        'Choose a new password',
        'Didn’t ask for this? You can safely ignore this email. Your password won’t change.'
      ),
    },
    'magic-link': {
      subject: 'Your Casanova Study sign-in link',
      html: make(
        'Your one-time sign-in link.',
        'Sign in to Casanova Study',
        'Click below to sign in. This link works once and expires soon.',
        'Sign me in',
        'Didn’t try to sign in? You can ignore this email.'
      ),
    },
    'change-email': {
      subject: 'Confirm your new email address',
      html: make(
        'Confirm the new email on your account.',
        'Confirm your new email',
        'Click below to confirm this as the new email address for your Casanova Study account.',
        'Confirm new email',
        'Didn’t request this change? Ignore this email and your address stays the same.'
      ),
    },
  }
}

// ── Parental consent (COPPA) ────────────────────────────────────────────────
// Sent when a student under 13 signs up; the link opens /parent-consent.

export function parentConsentEmail(e: { childName: string; childEmail: string; link: string; siteUrl: string }): { subject: string; html: string; text: string } {
  const child = escapeHtml(e.childName)
  const body = [
    heading(`${child} wants to use Casanova Study`),
    paragraph(`${child} (${escapeHtml(e.childEmail)}) created a Casanova Study account. Because they're under 13, they can't use it until a parent or guardian says it's OK.`),
    paragraph('Casanova Study turns class notes and topics into study guides, quizzes and practice, with an AI tutor that explains answers. We collect only what the app needs to work (name, email, birth date, what they study and how they answer), never show ads, and never sell personal information.', { muted: true }),
    button(e.link, 'Review and decide'),
    '<div style="height:24px;line-height:24px;">&nbsp;</div>',
    paragraph('The page explains exactly what we collect and lets you approve or decline. If you decline, the account and its data are deleted.', { muted: true, small: true }),
    linkFallback(e.link),
  ].join('\n')
  return {
    subject: `${e.childName} needs your OK to use Casanova Study`,
    html: emailLayout({
      preheader: `${e.childName} is under 13, so a parent needs to approve their Casanova Study account.`,
      body,
      footer: `You got this email because ${child} entered your address as their parent or guardian on Casanova Study. If that's not you, you can ignore it; the account stays locked.`,
      siteUrl: e.siteUrl,
    }),
    text: [
      `${e.childName} (${e.childEmail}) created a Casanova Study account. Because they're under 13, a parent or guardian needs to approve it first.`,
      '',
      `Review and decide: ${e.link}`,
      '',
      'If you decline, the account and its data are deleted. If this isn\'t you, ignore this email; the account stays locked.',
      '',
      'Casanova Study',
    ].join('\n'),
  }
}

// ── Review reminder ─────────────────────────────────────────────────────────
// Sent by the daily job (lib/reminders/run.ts) when Learn cards are due or a
// weak spot needs work. Every one carries a one-tap unsubscribe link.

export interface ReviewReminderEmail {
  firstName: string | null
  guides: { title: string; due: number; url: string }[]
  totalDue: number
  minutes: number
  weak: { topic: string; accuracy: number; url: string } | null
  streak: number
  startUrl: string
  unsubscribeUrl: string
  siteUrl: string
}

export function reviewReminderEmail(e: ReviewReminderEmail): { subject: string; html: string; text: string } {
  const cards = (n: number) => `${n} card${n === 1 ? '' : 's'}`
  const hi = e.firstName ? `${escapeHtml(e.firstName)}, ` : ''
  const streakLine = e.streak >= 2 ? `Keep your ${e.streak}-day streak going.` : ''
  const subject = e.totalDue > 0
    ? (e.streak >= 2 ? `${cards(e.totalDue)} to review. Keep your ${e.streak}-day streak` : `${cards(e.totalDue)} ready for review`)
    : `Time to practice ${e.weak?.topic ?? 'your weak spots'}`
  const headlineFor = (who: string) => e.totalDue > 0
    ? `${who}${cards(e.totalDue)} ${e.totalDue === 1 ? 'is' : 'are'} ready for review`
    : `${who}one weak spot to work on`
  const headline = headlineFor(hi)
  const intro = e.totalDue > 0
    ? `Reviewing right when you're about to forget is what makes it stick. About ${e.minutes} minute${e.minutes === 1 ? '' : 's'}. ${streakLine}`.trim()
    : `A short quiz on it now beats cramming later. ${streakLine}`.trim()

  const rows = e.guides.map((g) => `<tr>
      <td style="padding:12px 0;border-top:1px solid ${BRAND.line};font-family:${SANS};font-size:15px;line-height:21px;">
        <a href="${g.url}" style="color:${BRAND.ink};text-decoration:none;font-weight:600;">${escapeHtml(g.title)}</a>
      </td>
      <td align="right" style="padding:12px 0 12px 12px;border-top:1px solid ${BRAND.line};font-family:${SANS};font-size:13px;white-space:nowrap;">
        <a href="${g.url}" style="color:${BRAND.blue};text-decoration:none;font-weight:600;">${cards(g.due)} &rarr;</a>
      </td>
    </tr>`).join('\n')
  const guideList = e.guides.length
    ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:4px 0 28px 0;border-bottom:1px solid ${BRAND.line};">${rows}</table>`
    : ''

  const weakCard = e.weak
    ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:28px 0 8px 0;">
        <tr><td style="background-color:#fffbeb;border:1px solid #fde68a;border-radius:14px;padding:16px 18px;font-family:${SANS};">
          <div style="font-size:11px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;color:#b45309;">Weak spot</div>
          <div style="margin-top:6px;font-size:15px;line-height:22px;color:${BRAND.ink};"><strong>${escapeHtml(e.weak.topic)}</strong>: ${Math.round(e.weak.accuracy * 100)}% on your recent answers.</div>
          <div style="margin-top:8px;font-size:14px;"><a href="${e.weak.url}" style="color:#b45309;font-weight:600;text-decoration:none;">Practice it &rarr;</a></div>
        </td></tr>
      </table>`
    : ''

  const body = [
    heading(headline),
    paragraph(escapeHtml(intro), { muted: true }),
    guideList,
    e.totalDue > 0 ? button(e.startUrl, 'Start reviewing') : (e.weak ? button(e.weak.url, 'Practice it') : ''),
    e.totalDue > 0 ? weakCard : '',
  ].join('\n')

  return {
    subject,
    html: emailLayout({
      preheader: e.totalDue > 0 ? `About ${e.minutes} minutes to keep it fresh.` : 'A quick quiz on what you missed.',
      body,
      footer: `You get study reminders because you use Casanova Study. <a href="${e.unsubscribeUrl}" style="color:#94a3b8;text-decoration:underline;">Turn off reminders</a>`,
      siteUrl: e.siteUrl,
    }),
    text: [
      headlineFor(e.firstName ? `${e.firstName}, ` : ''),
      '',
      intro,
      '',
      ...e.guides.map((g) => `- ${g.title}: ${cards(g.due)} (${g.url})`),
      e.totalDue > 0 ? `\nStart reviewing: ${e.startUrl}` : '',
      e.weak ? `\nWeak spot: ${e.weak.topic}, ${Math.round(e.weak.accuracy * 100)}% recently. Practice it: ${e.weak.url}` : '',
      '',
      `Turn off reminders: ${e.unsubscribeUrl}`,
    ].join('\n'),
  }
}
