import { BRAND, button, emailLayout, escapeHtml, heading, linkFallback, paragraph } from './layout'

const SANS = "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"

const FORMAT_LABEL: Record<string, string> = {
  outline: 'Outline', flashcards: 'Flashcards', quiz: 'Quiz', summary: 'Summary', practice: 'Practice',
  plan: 'Study plan', cheatsheet: 'Cheat sheet', timeline: 'Timeline', custom: 'Study guide',
}

export interface ShareGuideEmail {
  senderName: string | null
  title: string
  format: string
  url: string
  message?: string
  siteUrl: string
}

export function shareGuideEmail(e: ShareGuideEmail): { subject: string; html: string; text: string } {
  const who = e.senderName ? escapeHtml(e.senderName) : 'Someone'
  const title = escapeHtml(e.title)
  const label = FORMAT_LABEL[e.format] ?? 'Study guide'
  const message = e.message?.trim()
    ? `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 24px 0;">
        <tr><td style="border-left:4px solid ${BRAND.blue};background-color:${BRAND.page};border-radius:0 10px 10px 0;padding:14px 18px;font-family:${SANS};font-size:15px;line-height:23px;color:${BRAND.body};font-style:italic;">
          &ldquo;${escapeHtml(e.message.trim()).replace(/\n/g, '<br>')}&rdquo;
          <div style="margin-top:6px;font-style:normal;font-size:13px;color:${BRAND.muted};">— ${who}</div>
        </td></tr>
      </table>`
    : ''

  const guideCard = `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0 0 28px 0;">
    <tr><td style="border:1px solid ${BRAND.line};border-radius:14px;padding:20px;background-color:#ffffff;">
      <span style="display:inline-block;font-family:${SANS};font-size:11px;font-weight:700;letter-spacing:1.2px;text-transform:uppercase;color:${BRAND.blue};background-color:${BRAND.soft};border-radius:999px;padding:4px 10px;">${label}</span>
      <div style="margin-top:10px;font-family:Georgia,'Times New Roman',serif;font-size:21px;line-height:28px;font-weight:600;color:${BRAND.ink};">${title}</div>
    </td></tr>
  </table>`

  const body = [
    heading(`${who} shared a study guide with you`),
    paragraph('Open it to study with flashcards, quizzes and practice — no download needed.', { muted: true }),
    guideCard,
    message,
    button(e.url, 'Open the study guide'),
    '<div style="height:24px;line-height:24px;">&nbsp;</div>',
    linkFallback(e.url),
  ].join('\n')

  return {
    subject: `${e.senderName || 'Someone'} shared “${e.title}” with you`,
    html: emailLayout({
      preheader: `${e.senderName || 'Someone'} shared a ${label.toLowerCase()} with you on Casanova Study.`,
      body,
      footer: `You got this email because ${who} shared a study guide with you on Casanova Study.`,
      siteUrl: e.siteUrl,
    }),
    text: [
      `${e.senderName || 'Someone'} shared a study guide with you: ${e.title}`,
      e.message?.trim() ? `\n"${e.message.trim()}"\n` : '',
      `Open it here: ${e.url}`,
      '',
      '— Casanova Study',
    ].join('\n'),
  }
}

// ── Supabase Auth templates ─────────────────────────────────────────────────
// Pasted into Supabase → Authentication → Emails → Templates. They use
// Supabase's Go-template variables, generated by scripts/build-auth-emails.ts.

export function authEmails(siteUrl: string): Record<string, { subject: string; html: string }> {
  const url = '{{ .ConfirmationURL }}'
  const make = (preheader: string, title: string, lead: string, cta: string, note: string) =>
    emailLayout({
      preheader,
      siteUrl,
      footer: 'You got this email because someone used this address on Casanova Study.',
      body: [heading(title), paragraph(lead), '<div style="height:8px;line-height:8px;">&nbsp;</div>', button(url, cta), '<div style="height:24px;line-height:24px;">&nbsp;</div>', paragraph(note, { muted: true, small: true }), linkFallback(url)].join('\n'),
    })
  return {
    'confirm-signup': {
      subject: 'Confirm your Casanova Study account',
      html: make(
        'One click to activate your account.',
        'Welcome to Casanova Study!',
        'You’re one step away from turning your notes, slides and topics into study guides, flashcards and quizzes. Confirm your email to activate your account.',
        'Confirm my email',
        'Didn’t sign up? You can ignore this email — no account will be activated.'
      ),
    },
    'reset-password': {
      subject: 'Reset your Casanova Study password',
      html: make(
        'Choose a new password for your account.',
        'Reset your password',
        'We got a request to reset the password for your Casanova Study account. Click below to choose a new one. The link works once and expires soon.',
        'Choose a new password',
        'Didn’t ask for this? You can ignore this email — your password won’t change.'
      ),
    },
    'magic-link': {
      subject: 'Your Casanova Study sign-in link',
      html: make(
        'Your one-time sign-in link.',
        'Sign in to Casanova Study',
        'Click below to sign in. This link works once and expires soon.',
        'Sign me in',
        'Didn’t try to sign in? You can ignore this email.'
      ),
    },
    'change-email': {
      subject: 'Confirm your new email address',
      html: make(
        'Confirm the new email on your account.',
        'Confirm your new email',
        'Click below to confirm this as the new email address for your Casanova Study account.',
        'Confirm new email',
        'Didn’t request this change? Ignore this email and your address stays the same.'
      ),
    },
  }
}
