-- Batch grading: papers graded together (a class set) share a batch_id, so the
-- class results page (/grade-exam/batch/[id]) can list them later. Generated by
-- the browser per batch; owner checks happen in the API (rows keep user_id).
ALTER TABLE grading_results ADD COLUMN IF NOT EXISTS batch_id uuid;
CREATE INDEX IF NOT EXISTS grading_results_batch_idx ON grading_results (batch_id) WHERE batch_id IS NOT NULL;
